### PR TITLE
Update Dockerfiles

### PR DESCRIPTION
**Pull request by omron93**
Provide same labels for all base image variants (CentOS, RHEL)
 - follow recomended labels from Project Atomic Container best practices
 - add summary and description labels - use ENV for simple using of same value in more descriptive labels
 - remove architecture label for RHEL based images (this label is set in RHEL image - no need to define it again)
                                           
(don't use separate instruction for each label)

Verify installed packages by `rpm -V`.

@hhorak @praiskup @pkubatrh Please take a look and merge.

### CODE REVIEW

**Comment by omron93** [comment]
To be able to verify installed packages, it is necessary to list all packages (no globbing). So I've listed them. @hhorak Is is really necessary to install them all?

**Comment by hhorak** [comment]
Let's try to install just `rh-varnish4-varnish`, the rest of the packages don't seem to have any real usage in container..

**Comment by omron93** [comment]
OK, thanks.

So `rh-varnish4-jemalloc-devel rh-varnish4-scldevel rh-varnish4-varnish-docs rh-varnish4-varnish-libs-devel` rpm packages won't be installed in image. It makes sense to me too,

**Comment by pkubatrh** [comment]
LGTM, merging.

**Pull request merged**
