### PR TITLE
Add Varnish version 5 for rhel/centos

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
Fedora tests fail due to Fedora version not having scl commands, which is expected.

**Comment by pkubatrh** [comment]
>@pkubatrh Why not to still share s2i scripts outside of version directory and using DOCKER_BUILD_CONTEXT = ..?

There are still some minor differences in the s2i scripts that would have to be removed first. This PR was just a simple sync with our internal repositories so no other changes have been done.

Maybe it would be worthwhile to make this into another distgen generated repository since we now have the option. But that would be out of scope of this PR.

**Comment by omron93** [comment]
Thanks for the explanation. Merging.

**Pull request merged**
