### PR TITLE
tests: use ct_init in container tests for preparing test env

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by zmiklank** [comment]
[test]

**Comment by phracek** [comment]
It looks like it relates only to container. So let's test only the container tests.

[test]

**Comment by phracek** [comment]
CentOS Stream 9 test is failing.

```bash
[1m[INFO] Cleaning up the test application...[0m

Error: Manager got SIGTERM
Debug: Stopping Child
Info: Child (28) ended
Info: Child (28) said Child dies
Debug: Child cleanup complete
Info: manager stopping child
Info: manager dies
5f55d5ed03976304696d20f72b94927f1e0d7d1aaa16917aea39c44d95dbf2b0
5f55d5ed03976304696d20f72b94927f1e0d7d1aaa16917aea39c44d95dbf2b0
rm: cannot remove '/tmp/tmp.hp56gvUoSX/tmp.fSBxuUIzSp.cid': No such file or directory
Test for image 'quay.io/sclorg/varnish-6-c9s:1' FAILED (exit code: 1)
-----------------------------------------------
Running test test_application_with_user (starting at 2023-02-20 12:54:10+00:00) ... 
-----------------------------------------------
```

Fedora test is failing as well.
```bash
[1m[INFO] Cleaning up the test application...[0m

Error: Manager got SIGTERM
Debug: Stopping Child
Info: Child (28) ended
Info: Child (28) said Child dies
Debug: Child cleanup complete
Info: manager stopping child
Info: manager dies
70306297ef4d5ae906b0ff3ff6ca9ede3d4235e3a09ef5f7bf99c27215c5b467
70306297ef4d5ae906b0ff3ff6ca9ede3d4235e3a09ef5f7bf99c27215c5b467
rm: cannot remove '/tmp/tmp.hrc6poQvTW/tmp.OAVRbpRovv.cid': No such file or directory
Test for image 'quay.io/fedora/varnish-6:0' FAILED (exit code: 1)
-----------------------------------------------
Running test test_application_with_user (starting at 2023-02-20 12:52:29+00:00) ... 
-----------------------------------------------

[1m[INFO] Waiting for application container to start...[0m
```

**Comment by zmiklank** [comment]
Good. This seems to be a reproducer also for https://github.com/sclorg/container-common-scripts/issues/326.

Will look into it.

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Review by phracek — APPROVED** [review]
LGTM

**Pull request merged**
