### PR TITLE
Move scl_enable back into versioned directories

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by omron93** [comment]
What is the motivation for this?

**Comment by pkubatrh** [comment]
Future proofing for varnish5 since the `scl_enable script` needs to enable specific version. Also as git is not being able to work with empty directories the missing `root/` folder broke downstream syncing (the `root/` is only created when making manpages upstream).

**Comment by pkubatrh** [comment]
Tests are green so merging this in.

**Comment by omron93** [comment]
Or something like this `source scl_source enable ${ENABLED_COLLECTIONS}` could be used. Some our images uses this and define ENABLED_COLLECTIONS is Dockerfile.

**Pull request merged**
