### PR TITLE
Replace docker with podman in s2i usage

### PR DESCRIPTION
**Pull request by hhorak**
SSIA

### CODE REVIEW

**Comment by phracek** [comment]
@hhorak Do we really need to mention `podman` in `s2i/bin/run` script? In case of package podman-docker is installed, then this is not needed. In the rest of all containers, we use docker. Can we close this issue?

**Comment by zmiklank** [comment]
> @hhorak Do we really need to mention `podman` in `s2i/bin/run` script? In case of package podman-docker is installed, then this is not needed. In the rest of all containers, we use docker. Can we close this issue?

I know that I am not hhorak, but I think we should indeed use `podman` in docs or usage information because we use `podman` internally (except for rhel7, centos7) even thoug we call it with `docker` alias. Podman, not docker, is also the supported container engine for RHEL releases.

**Review by phracek — APPROVED** [review]
LGTM.

**Comment by phracek** [comment]
[test]

**Comment by zmiklank** [comment]
I've rebased this on master so that we can run tests.
[test]

**Comment by zmiklank** [comment]
And added distgen-generated content.

[test]

**Pull request merged**
