### PR TITLE
Add generated directory for version 6

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
We do not keep the generated sources in the main branch. They are kept in the `generated` branch: https://github.com/sclorg/varnish-container/tree/generated/6

**Comment by phracek** [comment]
@pkubatrh You are absolutely right, but when we are trying to push changes into Quay.io, then either version does not exist in the main branch or in the generated branch does not exist Makefile where is BASE_IMAGE_NAME variable which is used for building. It can be hardcoded, but this is not the correct approach from my point of view.

**Comment by pkubatrh** [comment]
@phracek Right, but it feels really weird to force the repository to generate the source in the main branch just so you can grep a Makefile... I would actually be in favour of hardcoding the value, especially if we keep the github actions code for each repository separate.
Other idea - would it be possible to first read the value from the Makefile and then switch to the generated branch if it exists?

**Comment by phracek** [comment]
Closing this PR. actions/checkout@v2 provides a way how to fetch all github information and afterwards switch to 'generated' branch.

**Comment by phracek** [comment]
The new pull request with generated branch support https://github.com/sclorg/varnish-container/pull/75

**Pull request closed without merging**
