### PR TITLE
Add run_all_tests function

### PR DESCRIPTION
**Pull request by phracek**
This commit adds function to run all
tests and report results at the end.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by fila43** [comment]
From my point of view there miss checking results of tests in some cases.

**Comment by phracek** [comment]
@fila43 I have added more `check_result` checks. If something is missing, can you please point me?

[test]

**Comment by phracek** [comment]
Tests are passing. All issues were addressed. @fila43 Would you be willing to take a look at it one more time?

**Pull request merged**
