### PR TITLE
Remove files which are now generated.

### PR DESCRIPTION
**Pull request by omron93**
(#45 followup)

Generated sources are already in `generated` branch.

@pkubatrh Is something special needed to do to keep CentOS Community Container Pipeline working?

### CODE REVIEW

**Comment by pkubatrh** [comment]
>Is something special needed to do to keep CentOS Community Container Pipeline working?

Yes, you need to add a hook script to generate the repository content by distgen and make a PR against the container-index repository to enable the use of said hook.

Check these PRs for postgresql:
https://github.com/sclorg/postgresql-container/pull/203/commits/abbb5c575c2fc49bee9561a11f125251a515f0eb
https://github.com/sclorg/postgresql-container/pull/258
https://github.com/CentOS/container-index/pull/311

**Comment by pkubatrh** [comment]
>Generated sources are already in generated branch.

Given this is already done we should also modify the README file's links to point to the generated directory instead.

**Comment by omron93** [comment]
@pkubatrh Thanks. Updated. I hope it's ready now.

PR for container-index: https://github.com/CentOS/container-index/pull/335

**Comment by pkubatrh** [comment]
lgtm, thanks

**Comment by pkubatrh** [comment]
We should maybe wait with the merge until https://github.com/CentOS/container-index/pull/335 is closed

**Comment by omron93** [comment]
> We should maybe wait with the merge until CentOS/container-index#335 is closed

It's a question. Without change in this PR they probably won't be able to test it :-)

**Comment by pkubatrh** [comment]
Ah right, since the hook is in this PR as well... Ok lets merge this now.

**Pull request merged**
