### PR TITLE
Utilize more functions from test-lib.sh

### PR DESCRIPTION
**Pull request by hhorak**
**Warning: this requires https://github.com/sclorg/container-common-scripts/pull/238 to be merged first.**

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
This is already fixed and covered by https://github.com/sclorg/varnish-container/pull/103

**Pull request closed without merging**
