### PR TITLE
Add support building, testing, and pushing varnish-7

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for building, testing, and pushing varnish-7

### CODE REVIEW

**Comment by phracek** [comment]
No code change.
[test]

**Comment by phracek** [comment]
Rebased 

[test]

**Comment by zmiklank** [comment]
> The GitHub Action failed for this reason.
> 
> ```shell
> Installing collected packages: distgen
> Successfully installed distgen-1.14
> /home/runner/work/_temp/1e43e73a-96ac-4ed9-9286-8a1b128604d2.sh: line 5: ./common/tests/check_distgen_generated_files.sh: No such file or directory
> ```
> 
> When the distgen or container-common-scripts has some uncompatible change, we should file PR against all repos.
> 
> [test]

Are you sure you had your branch up to date? AFAIK the sources were updated properly.

**Comment by phracek** [comment]
> Are you sure you had your branch up to date? AFAIK the sources were updated properly.

@zmiklank No, common dir was not updated. Now all 8 checks passed.

**Comment by phracek** [comment]
@zmiklank Please let me know if this is fine.

**Comment by pkubatrh** [comment]
lgtm

**Pull request merged**
