### PR TITLE
Introduce distgen to varnish repo

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
@hhorak @omron93 ptal

**Comment by hhorak** [comment]
@uhliarik also FYI

**Comment by pkubatrh** [comment]
>@pkubatrh Why keeping generated sources was chosen?

Just to be able to see the diff of sources during this PR for easier review.

**Comment by omron93** [comment]
No objections, so merging.

**Pull request merged**
