### PR TITLE
deprecate c8s images, as EOL for c8s is 31th of May 2024

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Review by phracek — COMMENTED** [review]
Sometimes we use .exclude.c8s and sometimes we remove Dockerfile.c8s. Like https://github.com/sclorg/httpd-container/pull/211/files

**Comment by zmiklank** [comment]
> Sometimes we use .exclude.c8s and sometimes we remove Dockerfile.c8s. Like https://github.com/sclorg/httpd-container/pull/211/files

Yes, we remove Dockerfiles in distgen repos.
But I need to regenerate the content here, the check is failing.

**Comment by zmiklank** [comment]
[test]

**Review by phracek — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
